version: '3'
services:
  app:
    build:
      context: .
      dockerfile: infra/Dockerfile
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - database
  app2:
    build:
      context: .
      dockerfile: infra/Dockerfile
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - database
  web:
    image: nginx:1.25
    ports:
      - "8123:80"
    volumes:
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - app2
  database:
    image: mysql:8
    environment:
      MYSQL_USER: "alura"
      MYSQL_PASSWORD: "senhalura"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: "escalabilidade"
    ports:
      - "3306:3306"
    volumes:
      - ./infra/mysql:/var/lib/mysql
  mailpit:
    image: axllent/mailpit:v1.6.13
    ports:
      - "1025:1025"
      - "8025:8025"
  cache:
    image: redis:7
